name: Deploy to GitHub Pages

on:
  push:
    branches:
      - normanCanvas # â† tu rama personalizada

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup publish directory
        run: |
          mkdir public
          cp -r dist/* public/
          rm -rf public/.git public/.github

      - name: List files for debugging
        run: ls -la public

      - name: Deploy to GitHub Pages ğŸš€
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
